# Generated by Django 6.0.7 on 2026-08-14 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiftTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(choices=[('LIFT AND JERK', 'LJ'), ('OVERHEAD THROW', 'OVHD Thr (m)'), ('CHEST THROW', 'CHST Thr (m)'), ('OVERHEAD SQUAT', 'OVHD SQT'), ('LUNGE MATRIX', 'Lunge MTRX'), ('PUSH UP HOLD HIGH', 'Push up Hld H (s)'), ('PUSH UP HOLD LOW', 'Push up Hld L (s)'), ('PUSH UP REPS', 'Push up Reps'), ('SQUAT', 'SQT (reps)'), ('WALL SIT', 'Wall Sit (s)'), ('DEAD HANG', 'Dead Hang (s)'), ('ISOMETRIC HOLD RIGHT', 'ISO Hld R (s)'), ('ISOMETRIC HOLD LEFT', 'ISO Hld L (s)')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200)),
                ('DOB', models.DateField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('A', 'Accelaration (0-30m)'), ('B', 'Max Velocity (30-60m)'), ('C', 'Speed Endurance / Technique + Endurance'), ('D', 'Capacity/Tempo'), ('E', 'Rhythm/ Mechanics / Rhythm'), ('F', 'Strength'), ('G', 'Power / Elastic'), ('R', 'Recovery')], max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TrackTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(choices=[('100M', '100m'), ('200M', '200m'), ('VERTICAL', 'Vert (in)'), ('SINGLE LEG HOLD RIGHT', 'SL Hld R (s)'), ('SINGLE HOLD LEFT', 'SL Hld L (s)'), ('SINGLE LEG BOUND', 'SL Bound (s)'), ('CORE', 'Core (reps)'), ('FLY ZONE', 'Fly Zone (s)'), ('SPRINT MOBILITY', 'Sprint Mobility'), ('AGILITY', 'Agility')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutDrill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sets', models.IntegerField(blank=True)),
                ('repetitions', models.IntegerField(blank=True)),
                ('distance', models.IntegerField(blank=True)),
                ('duration', models.IntegerField(blank=True)),
                ('phase', models.CharField(blank=True, choices=[('base', 'Base'), ('buid', 'Build'), ('peak', 'Peak')])),
                ('workout', models.CharField(blank=True, choices=[('warm up', 'Warm up'), ('mobility', 'Mobility'), ('cool down', 'Cool Down'), ('hips', 'Hips'), ('core', 'Core'), ('med ball', 'Med Ball'), ('sled', 'Sled'), ('plyo', 'Plyo'), ('posture', 'Posture'), ('sprint reaction', 'Sprint Reaction'), ('wall drills', 'Wall Drills')])),
            ],
        ),
        migrations.CreateModel(
            name='LiftTestData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('time', models.IntegerField(blank=True, null=True)),
                ('test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ngoma.lifttest')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngoma.profiledata')),
            ],
        ),
        migrations.CreateModel(
            name='TrackTestData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('time', models.IntegerField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngoma.profiledata')),
                ('test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ngoma.tracktest')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngoma.profiledata')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngoma.session')),
            ],
            options={
                'unique_together': {('player', 'session')},
            },
        ),
    ]
