# Generated by Django 6.0.7 on 2026-08-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngoma', '0002_menucategory_alter_session_session_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.AddField(
            model_name='workoutdrill',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
