# Generated by Django 6.0.7 on 2026-08-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngoma', '0003_upload_workoutdrill_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutdrill',
            name='prescription',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
