# Generated by Django 6.0.7 on 2026-08-24 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngoma', '0004_workoutdrill_prescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutdrill',
            name='order',
        ),
    ]
