# Generated by Django 6.0.7 on 2026-08-24 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngoma', '0005_remove_workoutdrill_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutdrill',
            name='menu',
        ),
    ]
