# Generated by Django 6.0.7 on 2026-08-25 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngoma', '0006_remove_workoutdrill_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PhaseChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='workoutdrill',
            name='workout',
        ),
        migrations.AlterField(
            model_name='lifttest',
            name='test',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tracktest',
            name='test',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='workoutdrill',
            name='block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ngoma.blockchoice'),
        ),
        migrations.AlterField(
            model_name='workoutdrill',
            name='phase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ngoma.phasechoice'),
        ),
    ]
