# Generated by Django 6.0.7 on 2026-08-25 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngoma', '0007_blockchoice_phasechoice_remove_workoutdrill_workout_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blockchoice',
            old_name='name',
            new_name='block',
        ),
        migrations.RenameField(
            model_name='phasechoice',
            old_name='name',
            new_name='phase',
        ),
        migrations.RemoveField(
            model_name='workoutdrill',
            name='phase',
        ),
        migrations.AddField(
            model_name='blockchoice',
            name='phase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ngoma.phasechoice'),
        ),
    ]
