# Generated by Django 6.0.7 on 2026-08-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngoma', '0008_rename_name_blockchoice_block_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategory',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menusubcategory',
            name='blocks',
            field=models.ManyToManyField(to='ngoma.blockchoice'),
        ),
        migrations.AddField(
            model_name='phasechoice',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
