# Generated by Django 6.0.7 on 2026-08-26 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngoma', '0009_menucategory_notes_menusubcategory_blocks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menusubcategory',
            name='blocks',
        ),
        migrations.CreateModel(
            name='MenuOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocks', models.CharField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngoma.menusubcategory')),
            ],
        ),
    ]
