# Generated by Django 6.0.7 on 2026-08-26 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngoma', '0010_remove_menusubcategory_blocks_menuoptions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MenuOptions',
            new_name='MenuOption',
        ),
        migrations.RenameField(
            model_name='menuoption',
            old_name='blocks',
            new_name='block',
        ),
    ]
