# Generated by Django 6.0.7 on 2026-08-30 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngoma', '0011_rename_menuoptions_menuoption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockchoice',
            name='phase',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ngoma.phasechoice'),
            preserve_default=False,
        ),
    ]
