# Generated by Django 6.0.7 on 2026-09-12 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngoma', '0012_alter_blockchoice_phase'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendAnalyses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analyses', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='TrendTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(max_length=200)),
                ('analyses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ngoma.trendanalyses')),
            ],
        ),
        migrations.CreateModel(
            name='CISTI_score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consistency', models.IntegerField()),
                ('intensity', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('technique', models.IntegerField()),
                ('intent', models.IntegerField()),
                ('overall', models.IntegerField()),
                ('test', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ngoma.trendtest')),
            ],
        ),
    ]
