# Generated by Django 6.0.7 on 2026-09-12 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngoma', '0013_trendanalyses_alter_attendance_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendtest',
            name='athlete',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ngoma.profiledata'),
        ),
    ]
