# Generated by Django 6.0.7 on 2026-09-14 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngoma', '0014_trendtest_athlete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifttestdata',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngoma.lifttest'),
        ),
        migrations.AlterField(
            model_name='tracktestdata',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngoma.tracktest'),
        ),
    ]
