# Generated by Django 6.0.7 on 2026-09-14 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngoma', '0015_alter_lifttestdata_test_alter_tracktestdata_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lifttestdata',
            old_name='time',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='tracktestdata',
            old_name='time',
            new_name='value',
        ),
    ]
