# Generated by Django 6.0.7 on 2026-09-16 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngoma', '0017_alter_cisti_score_consistency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trendtest',
            name='analyses',
        ),
        migrations.RemoveField(
            model_name='trendtest',
            name='athlete',
        ),
        migrations.CreateModel(
            name='TrendTestData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('analyses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ngoma.trendanalyses')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngoma.profiledata')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngoma.trendtest')),
            ],
        ),
    ]
