# Generated by Django 6.0.7 on 2026-09-16 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngoma', '0018_remove_trendtest_analyses_remove_trendtest_athlete_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trendtestdata',
            old_name='athlete',
            new_name='profile',
        ),
    ]
