# Generated by Django 6.0.7 on 2026-09-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngoma', '0019_rename_athlete_trendtestdata_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trendtestdata',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
