# Generated by Django 6.0.7 on 2026-09-22 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngoma', '0020_alter_trendtestdata_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cisti_score',
            old_name='consistency',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='cisti_score',
            name='intensity',
        ),
        migrations.RemoveField(
            model_name='cisti_score',
            name='intent',
        ),
        migrations.RemoveField(
            model_name='cisti_score',
            name='overall',
        ),
        migrations.RemoveField(
            model_name='cisti_score',
            name='speed',
        ),
        migrations.RemoveField(
            model_name='cisti_score',
            name='technique',
        ),
        migrations.AddField(
            model_name='cisti_score',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cisti_score',
            name='metric',
            field=models.CharField(choices=[('Consistency', 'C'), ('Intensity', 'I'), ('Speed', 'S'), ('Technique', 'T'), ('Intent', 'I'), ('Overall', 'Overall')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cisti_score',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cisti_score',
            name='test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ngoma.trendtestdata'),
            preserve_default=False,
        ),
    ]
