# Generated by Django 6.0.7 on 2026-09-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngoma', '0021_rename_consistency_cisti_score_value_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cisti_score',
            old_name='value',
            new_name='score',
        ),
        migrations.AlterField(
            model_name='cisti_score',
            name='metric',
            field=models.CharField(choices=[('C', 'Consistency'), ('I', 'Intensity'), ('S', 'Speed'), ('T', 'Technique'), ('I', 'Intent'), ('Overall', 'Overall')]),
        ),
    ]
