# Generated by Django 6.0.7 on 2026-09-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngoma', '0022_rename_value_cisti_score_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cisti_score',
            name='metric',
            field=models.CharField(choices=[('C', 'Consistency'), ('IN', 'Intensity'), ('S', 'Speed'), ('T', 'Technique'), ('I', 'Intent'), ('Overall', 'Overall')]),
        ),
    ]
