# Generated by Django 6.0.7 on 2026-09-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngoma', '0023_alter_cisti_score_metric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trendtestdata',
            name='date',
            field=models.DateField(),
        ),
    ]
