# Generated by Django 6.0.7 on 2026-09-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngoma', '0024_alter_trendtestdata_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='drills',
            field=models.ManyToManyField(blank=True, to='ngoma.workoutdrill'),
        ),
        migrations.RemoveField(
            model_name='session',
            name='session_type',
        ),
        migrations.AddField(
            model_name='session',
            name='session_type',
            field=models.ManyToManyField(to='ngoma.menucategory'),
        ),
    ]
