# Generated by Django 6.0.7 on 2026-09-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngoma', '0025_session_drills_remove_session_session_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutdrill',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
