# Generated by Django 6.0.7 on 2026-10-02 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngoma', '0026_workoutdrill_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='profiledata',
            name='workout_category',
            field=models.ManyToManyField(to='ngoma.menucategory'),
        ),
        migrations.AddField(
            model_name='profiledata',
            name='client_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ngoma.clientcategory'),
        ),
    ]
