# Generated by Django 6.0.7 on 2026-10-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngoma', '0027_clientcategory_profiledata_workout_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='profiledata',
            name='workout_category',
            field=models.ManyToManyField(to='ngoma.workoutcategory'),
        ),
    ]
