# Generated by Django 6.0.7 on 2026-10-02 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngoma', '0028_workoutcategory_alter_profiledata_workout_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='WorkoutCategory',
        ),
        migrations.AlterField(
            model_name='profiledata',
            name='workout_category',
            field=models.ManyToManyField(to='ngoma.menucategory'),
        ),
        migrations.AddField(
            model_name='profiledata',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ngoma.status'),
        ),
    ]
