# Generated by Django 6.0.7 on 2026-10-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngoma', '0029_status_delete_workoutcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledata',
            name='image',
            field=models.ImageField(default=1, upload_to=None),
            preserve_default=False,
        ),
    ]
