# Generated by Django 6.0.7 on 2026-10-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngoma', '0030_profiledata_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Workout categories',
            },
        ),
        migrations.AlterModelOptions(
            name='clientcategory',
            options={'verbose_name_plural': 'Client categories'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'status'},
        ),
        migrations.RemoveField(
            model_name='profiledata',
            name='workout_category',
        ),
        migrations.AddField(
            model_name='session',
            name='menu_type',
            field=models.ManyToManyField(to='ngoma.menucategory'),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_type',
            field=models.ManyToManyField(to='ngoma.workoutcategory'),
        ),
    ]
