# Generated by Django 6.0.7 on 2026-10-02 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngoma', '0031_workoutcategory_alter_clientcategory_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CISTI_score',
            new_name='CISTIScore',
        ),
        migrations.AlterModelOptions(
            name='lifttestdata',
            options={'verbose_name_plural': 'Lift Test Data'},
        ),
        migrations.AlterModelOptions(
            name='menucategory',
            options={'verbose_name_plural': 'Menu Categories'},
        ),
        migrations.AlterModelOptions(
            name='menusubcategory',
            options={'verbose_name_plural': 'Menu SubCategories'},
        ),
        migrations.AlterModelOptions(
            name='profiledata',
            options={'verbose_name_plural': 'Profile Data'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'Status'},
        ),
        migrations.AlterModelOptions(
            name='tracktestdata',
            options={'verbose_name_plural': 'Track Test Data'},
        ),
        migrations.AlterModelOptions(
            name='trendanalyses',
            options={'verbose_name_plural': 'Trend Analyses'},
        ),
    ]
