# Generated by Django 6.0.7 on 2026-10-04 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngoma', '0033_macrocycle_seasonphase_trainingblock_trainingtheme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingblock',
            name='theme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ngoma.trainingtheme'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingblock',
            name='week',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ngoma.trainingweek'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingtheme',
            name='macrocycle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ngoma.macrocycle'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingweek',
            name='macrocycle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ngoma.macrocycle'),
            preserve_default=False,
        ),
    ]
