# Generated by Django 6.0.7 on 2026-10-04 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngoma', '0034_trainingblock_theme_trainingblock_week_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='macrocycle',
            name='athlete',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ngoma.profiledata'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='macrocycle',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
