# Generated by Django 6.0.7 on 2026-10-05 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngoma', '0035_macrocycle_athlete_macrocycle_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('protocol', models.CharField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, null=True)),
                ('direction', models.CharField(blank=True, null=True)),
                ('attempts', models.CharField(blank=True, null=True)),
                ('equipment', models.CharField(blank=True, null=True)),
                ('classification', models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='lifttest',
            name='classification',
            field=models.CharField(choices=[('UNIVERSAL', 'Universal'), ('OPTIONAL', 'Optional'), ('SPORT-SPECIFIC', 'Sport-specific')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tracktest',
            name='classification',
            field=models.CharField(choices=[('UNIVERSAL', 'Universal'), ('OPTIONAL', 'Optional'), ('SPORT-SPECIFIC', 'Sport-specific')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trendtest',
            name='classification',
            field=models.CharField(choices=[('UNIVERSAL', 'Universal'), ('OPTIONAL', 'Optional'), ('SPORT-SPECIFIC', 'Sport-specific')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lifttest',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngoma.testname'),
        ),
        migrations.AlterField(
            model_name='tracktest',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngoma.testname'),
        ),
        migrations.AlterField(
            model_name='trendtest',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngoma.testname'),
        ),
        migrations.AlterField(
            model_name='trendtestdata',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngoma.testname'),
        ),
        migrations.AddField(
            model_name='testname',
            name='quality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ngoma.testquality'),
        ),
    ]
