# Generated by Django 6.0.7 on 2026-10-06 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngoma', '0036_testname_testquality_lifttest_classification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='macrocycle',
            name='athlete',
        ),
        migrations.CreateModel(
            name='ProfileMacrocycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('macrocycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngoma.macrocycle')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngoma.profiledata')),
                ('program_phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ngoma.phasechoice')),
                ('season_phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ngoma.seasonphase')),
            ],
        ),
        migrations.AlterField(
            model_name='trainingtheme',
            name='macrocycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngoma.profilemacrocycle'),
        ),
        migrations.AlterField(
            model_name='trainingweek',
            name='macrocycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngoma.profilemacrocycle'),
        ),
    ]
