# Generated by Django 6.0.7 on 2026-10-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngoma', '0037_remove_macrocycle_athlete_profilemacrocycle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='macrocycle',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingblock',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingtheme',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workoutdrill',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workoutdrill',
            name='distance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workoutdrill',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workoutdrill',
            name='prescription',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='workoutdrill',
            name='repetitions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workoutdrill',
            name='sets',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
