# Generated by Django 6.0.7 on 2026-10-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngoma', '0038_alter_attendance_notes_alter_macrocycle_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledata',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
    ]
