# Generated by Django 6.0.7 on 2026-10-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngoma', '0039_alter_profiledata_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='macrocycle',
            name='end',
        ),
        migrations.RemoveField(
            model_name='macrocycle',
            name='start',
        ),
        migrations.RemoveField(
            model_name='session',
            name='time',
        ),
        migrations.RemoveField(
            model_name='trainingweek',
            name='end',
        ),
        migrations.RemoveField(
            model_name='trainingweek',
            name='start',
        ),
        migrations.AddField(
            model_name='macrocycle',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='macrocycle',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingtheme',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingtheme',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingweek',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingweek',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
