# Generated by Django 6.0.7 on 2026-10-08 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngoma', '0040_remove_macrocycle_end_remove_macrocycle_start_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingblock',
            name='week',
        ),
        migrations.AddField(
            model_name='trainingblock',
            name='week',
            field=models.ManyToManyField(to='ngoma.trainingweek'),
        ),
    ]
