# Generated by Django 6.0.7 on 2026-10-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngoma', '0041_remove_trainingblock_week_trainingblock_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
