# Generated by Django 6.0.7 on 2026-10-09 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngoma', '0042_session_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingblock',
            old_name='block',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='trainingtheme',
            old_name='theme',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='macrocycle',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='trainingblock',
            name='week',
        ),
        migrations.RemoveField(
            model_name='trainingtheme',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='trainingtheme',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='trainingweek',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='trainingweek',
            name='start_date',
        ),
        migrations.AddField(
            model_name='macrocycle',
            name='estimated_weeks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilemacrocycle',
            name='availability',
            field=models.CharField(choices=[('available', 'AVAILABILITY'), ('unavailable', 'UNAVAILABLE'), ('injured', 'INJURED')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingblock',
            name='end_week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainingblock_end_week', to='ngoma.trainingweek'),
        ),
        migrations.AddField(
            model_name='trainingblock',
            name='start_week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainingblock_start_week', to='ngoma.trainingweek'),
        ),
        migrations.AddField(
            model_name='trainingtheme',
            name='end_week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainingtheme_end_week', to='ngoma.trainingweek'),
        ),
        migrations.AddField(
            model_name='trainingtheme',
            name='start_week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainingtheme_start_week', to='ngoma.trainingweek'),
        ),
    ]
