# Generated by Django 6.0.7 on 2026-07-30 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platform1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coach',
            new_name='Staff',
        ),
    ]
